/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExportDialog.java
 *
 * Created on 23-nov-2010, 17.30.36
 */

package it.francescogabbrielli.torusapplet;

import java.io.File;
import java.io.FileInputStream;
import java.io.PrintWriter;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Francesco Gabbrielli
 */
public class ExportDialog extends javax.swing.JDialog {

	private File file ;

	
    /** Creates new form ExportDialog */
    public ExportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

	public void setDir(File homeDir) {
		if(homeDir!=null)
			jFileChooser1.setCurrentDirectory(homeDir);
	}

	public File getDir() {
		return file!=null ? file.getParentFile() : jFileChooser1.getCurrentDirectory() ;
	}
	

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        translateCheck = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        resizeSpinner = new javax.swing.JSpinner();
        runCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export Points");

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        translateCheck.setSelected(true);
        translateCheck.setText("Translate in (0,0,0)");
        jPanel1.add(translateCheck);

        jLabel1.setText("   Size");
        jPanel1.add(jLabel1);

        resizeSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        resizeSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resizeSpinner.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(resizeSpinner);

        runCheck.setSelected(true);
        runCheck.setText("Run vcs");
        jPanel1.add(runCheck);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
		if(evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
			file = jFileChooser1.getSelectedFile() ;
			dispose();
		} else if(evt.getActionCommand().equals(JFileChooser.CANCEL_SELECTION)) {
			file = null ;
			dispose() ;
		}
	}//GEN-LAST:event_jFileChooser1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner resizeSpinner;
    private javax.swing.JCheckBox runCheck;
    private javax.swing.JCheckBox translateCheck;
    // End of variables declaration//GEN-END:variables

	public void setSystem(SimulationSystem s) {
		resizeSpinner.setValue(s.getRadius());
	}

	public double getRadius() {
		return (Double) resizeSpinner.getValue() ;
	}

	public boolean isTranslated() {
		return translateCheck.isSelected() ;
	}

	public File getFile() {
		return file;
	}

	public boolean isRun() {
		return runCheck.isSelected() ;
	}

}
